# Generated by Django 4.2.7 on 2023-11-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('priceLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('email', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=64)),
                ('priceLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionName', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamsterapp.categories')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamsterapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamsterapp.users'),
        ),
    ]
